element-settings:
  fire:
    passive:

    enchant:

  ice:
    passive:

    enchant:

  earth:
    passive:
      mining-power: true
      mining-power-setting:
        #If "mining-power-drop" is true, heated items are automatically dropped to the ground. if false, items are added to the inventory.
        drop: true

        copper-xp: 0.5
        iron-xp: 0.7
        gold-xp: 1
        debris-xp: 2

    enchant:

  air:
    passive:

    enchant: